### ISSUE TITLE
Create an about us page

### ISSUE THREAD

**Issue by jzeng4ub** [jianzhaojohn/Habit-Rabbit#103]
Link to github, set up button in hamburger menu that links to about us

**Comment by suhuboice** [comment]
Hello, I am the one that help you with this issue. Is there any way I can contact you and talk about this issue?

**Comment by jzeng4ub** [comment]
Sure, what's the issue?

**Comment by suhuboice** [comment]
#103 This hamburger issue:)

**Comment by jzeng4ub** [comment]
If you look at the home page, the one with the house on it, at the top left, there is a button that will open up a menu that shows other pages and settings. You are to implement an about us page, then add a button to this menu, then link to the about us page to this button. The XML file for the hamburger menu is located at Habit-Rabbit/app/src/main/res/menu/navigation_menu.xml.

**Comment by suhuboice** [comment]
Do you have time tomorrow? Can we meet and talk about it?

**Comment by jzeng4ub** [comment]
Sure, I can meet from 10 AM to 3 PM and from 4 PM onwards.

**Comment by suhuboice** [comment]
Can we meet 5pm at Capen library?

**Comment by jzeng4ub** [comment]
Ok.

**Comment by jzeng4ub** [comment]
What is your UBIT?

**Comment by suhuboice** [comment]
shuoqian. I also need yours:)  Sorry for the late response.
