### ISSUE TITLE
Enhance the security

### ISSUE THREAD

**Issue by littletoe** [jianzhaojohn/Habit-Rabbit#106]
adding more restrictions to password when sign up and notice the user in a proper way (eg. adding a text view in the register page showing the polices or pop up a hint showing why a password is invalidate).

- Password should be more the 8 characters long;
- Password should contains all lower case, upper case and special characters;
- Password should not be the same with username and so on.

**Comment by littletoe** [comment]
password should 1) be more the 8 characters long; 2) contains all lower case, upper case and special characters; 3) is not the same as username and so on.

**Comment by ankitner** [comment]
#157  I have made a pull request to the branch:password
