### ISSUE TITLE
Notify users when they've completed a habit and prevent them from entering that they completed it more than they already have

### ISSUE THREAD

**Issue by arogers7** [jianzhaojohn/Habit-Rabbit#114]

**Comment by Deepaklather** [comment]
I do not know what you want to get changed in your app? Can you explain it more clearly or can we meet in campus anytime to solve this issue?

**Comment by arogers7** [comment]
Yep! Let me know if you need any more info

**Comment by Deepaklather** [comment]
![image](https://user-images.githubusercontent.com/36175612/38168441-d2f6d208-3519-11e8-89b1-f5af71bbe4bb.png)

**Comment by Deepaklather** [comment]
I made a text field of Input day. Do you want it like this?  

if you are able to see the picture then please go to the preview section.

**Comment by arogers7** [comment]
No, I meant a modification of the habit input section, which you can access through the agenda.

**Comment by Deepaklather** [comment]
Can we meet on Monday anytime after 12 O'clock? I just want to know what modifications exactly you want.

**Comment by arogers7** [comment]
Sure, I'm free 1-2 and after class at 5.

**Comment by Deepaklather** [comment]
Can we meet right after the class today?

**Comment by arogers7** [comment]
Sure, I'll stay in my seat. I'm in the third row from the front, on the innermost seat.

**Comment by Deepaklather** [comment]
ok

**Comment by Deepaklather** [comment]
Bro I am outside. Can you come out of the class?
