### ISSUE TITLE
Bug on Bio: Using an android phone: Samsung S7

### ISSUE THREAD

**Issue by ArodyDel** [jianzhaojohn/Habit-Rabbit#144]
Description: When I try to edit my bio under the profile tab and hit done to save it. Going back to my profile doesn't save my edit.

Steps to Reproduce: 
1: go to profile tab
2: go type in User Bio here
3.hit done on the keyboard
4:go to main menu of app
5:return to profile tab

Expected behavior: bio is saved

Actual behavior: still empty

Reproduces how often: 100%

**Comment by sunnyxu715** [comment]
Hi, thanks for reporting the bug, we will look into it

**Comment by sunnyxu715** [comment]
Hi, this is not a bug since it is not a mvp feature of our app, but we will implement this function for official release
