### ISSUE TITLE
[Feature Request] When adding a habit

### ISSUE THREAD

**Issue by rmredder** [jianzhaojohn/Habit-Rabbit#161]
Change the text in Title and Description text boxes to a hint so the user does not need to delete the text themselves. 

Picture of activity I am referencing.
![image](https://user-images.githubusercontent.com/31999343/39060305-fc3b3b02-448e-11e8-93d0-5f6bdfff1867.png)

**Comment by littletoe** [comment]
We fill these fields in case someone is too lazy to type something.
