### ISSUE TITLE
Feature Request: Decrementer

### ISSUE THREAD

**Issue by aforthma** [jianzhaojohn/Habit-Rabbit#163]
Currently, selecting a check mark for a habit in the agenda will increment the occurrence. However, if a habit was checked by mistake, it doesn't look like there's a way to decrement the value. So maybe instead of a check, it could be a plus and minus. You could make the plus a lot bigger than the minus so it's easier to hit the expected default option while still having a way to correct a mistake.

**Comment by littletoe** [comment]
We will take this into consideration.
Thanks for your suggestion!
